### PR TITLE
New line should separate sentences to make translation easier

### PR DESCRIPTION
**Pull request by noisy**
It was [already proven](https://github.com/progit/progit2/pull/331) during translation of much bigger text - a Pro Git 2 book - that it is much easier to translate text sentence by sentence.

Knowing how much difficult this could be to review, I have prepared two commits:
- "Removed double spaces and trailing spaces", which could be very easily reviewed by seeing: https://github.com/noisy/steem-bluepaper-pl/commit/873d4841d15e2a26208abae9a9720d4eeaba8272
  or
  https://github.com/noisy/steem-bluepaper-pl/commit/873d4841d15e2a26208abae9a9720d4eeaba8272?w=1 which uses [?w=1 github feature](https://github.com/blog/967-github-secrets), which ignores whitespaces (that's why commit with that shows as empty)

- second commit 4037affa78348d178633c8159c83862602aaa1c5 - "Split text into sentences (one per line), to make translation easier" can be examined manually or by written by my special check script: https://gist.github.com/noisy/1f30761450310c698fcacc23ea8a6f9d to prove, that only newlines were changed.

Just run:

```
wget https://gist.githubusercontent.com/noisy/1f30761450310c698fcacc23ea8a6f9d/raw/452c4f5732040ff0edb39f4a2a7dc7ea93320944/new-lines-check.py
python new-lines-check.py
```

I want to emphasize one fact, that every changed line were examined manually. Script was written in that way, that it proves, that commit contains only changes with new lines.

### CODE REVIEW

**Comment by testzcrypto** [comment]
It's really doesn't matter if you use translation systems like Crowdin. We setup such system for Steem Bluepaper, please look:
[**Join Steem Bluepaper translation project!**](https://steemit.com/bookchain/@bookchain/join-steem-bluepaper-translation-project)

**Comment by noisy** [comment]
@testzcrypto Bluepaper will be a living document. I think it will be much easier to apply changes, if they can be compared line by line.

And, if it doesn't matter for Crowdin, then this should not be a problem to it.

**Comment by testzcrypto** [comment]
@noisy Yes, for living document it's make more sense than for translation. I also doesn't see much sense with tags for PDF generation, for my opinion regular Markdown enough for documents and make editing and updating much more easy.

**Comment by plink01001** [comment]
Looks good! Thanks for the change.

**Pull request merged**
